baseURL = 'https://sterchelen.net/'
languageCode = 'en-us'
title = 'sterchelen.net | learn technical stuff'
theme = "smol"

[markup.goldmark.renderer]
unsafe= true


# Parameters
[params]
    subtitle = "Learn by sharing, share by learning"
    dateFmt = "02.01.2006 15:04"
		mode="auto"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume/my-resume.pdf"
        weight = 2 

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "My links"
        url = "https://links.sterchelen.net"
        weight = 1 
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/sterchelen"
        weight = 2 
    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/sterchelen"
        weight = 3 
